name: Lijter

on: push

jobs:
  tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # If there's an action_req.txt file, install whatever's on there
        #   for unit tests
        if [ -f actions_req.txt ]; then pip install -r actions_req.txt; fi
    - name: Test with pytest
      run: |
        pytest
  lints:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f actionsReq.txt ]; then pip install -r actionsReq.txt; fi
        
    - name: Flake8
      run: |
        # stop if there are any syntax errors
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./"
