name: "pre-commit - formatting autofix"
on:
  workflow_run:
    workflows: ["Python Testrunner"]
    branches: [main]
    types:
      - completed

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install pre-commit
      run: |
        pip install pre-commit

    - name: Run pre-commit
      run: |
        pre-commit run --all-files

    - name: Push to GitHub Pages
      continue-on-error: true
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "chore: fixes from pre-commit" -a
        git push origin HEAD:main
