# This workflow runs whatever unit tests might exist.

name: Python Testrunner

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # If there's an action_req.txt file, install whatever's on there
        #   for unit tests
        if [ -f actions_req.txt ]; then pip install -r actions_req.txt; fi
    - name: Test with pytest
      run: |
        pytest
